import esbuild from "esbuild";
import { copyFile, mkdir } from "fs/promises";
import { join, resolve } from "path";
import process from "process";
import { buildStyles } from "./scripts/build-styles.mjs";

const srcAliases = {
  "@core": resolve("src/core"),
  "@application": resolve("src/application"),
  "@adapters": resolve("src/adapters"),
  "@apps": resolve("src/apps"),
  "@shared": resolve("src/shared"),
  "@manifest": resolve("manifest.json"),
};

/*
 * Dependencies may import Node built-ins on code paths this plugin never
 * reaches (the Anthropic SDK loads credentials from disk only when no API key
 * is supplied). Aliasing them keeps `require("fs")` out of the mobile bundle.
 */
const nodeShims = {
  fs: resolve("shims/nodeUnavailable.mjs"),
  "node:fs": resolve("shims/nodeUnavailable.mjs"),
  path: resolve("shims/nodeUnavailable.mjs"),
  "node:path": resolve("shims/nodeUnavailable.mjs"),
};

const production = process.argv[2] === "production";
const watch = process.argv.includes("--watch");
const defaultOutputDir = resolve("dist");
const pluginOutputDir = process.env.ATTEST_OUTPUT_DIR ?? defaultOutputDir;
const pluginOutputFile = join(pluginOutputDir, "main.js");

const banner =
  "/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nif you want to view the source, please visit the plugin repository\n*/";

async function copyPluginAssets() {
  await mkdir(pluginOutputDir, { recursive: true });
  await Promise.all([
    copyFile("manifest.json", join(pluginOutputDir, "manifest.json")),
    buildStyles(join(pluginOutputDir, "styles.css")),
  ]);
}

await mkdir(pluginOutputDir, { recursive: true });

const context = await esbuild.context({
  alias: { ...srcAliases, ...nodeShims },
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["src/apps/obsidian/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: pluginOutputFile,
  platform: "browser",
  plugins: [
    {
      name: "copy-plugin-assets",
      setup(build) {
        build.onEnd(async () => {
          await copyPluginAssets();
        });
      },
    },
  ],
  sourcemap: production ? false : "inline",
  target: "es2018",
  treeShaking: true,
});

if (watch) {
  await context.watch();
  console.log(`Watching for changes and writing artifacts to ${pluginOutputDir}...`);
} else {
  await context.rebuild();
  await context.dispose();
}
