import builtins from "builtin-modules";
import esbuild from "esbuild";
import { copyFile, mkdir } from "fs/promises";
import { homedir } from "os";
import { join, resolve } from "path";
import process from "process";

// Path aliases mirror tsconfig.json "paths" and vitest.config.ts so the same
// import specifiers resolve identically under tsc, the bundle, and tests.
// esbuild remaps subpaths automatically (e.g. "@core/research/x" -> src/core/research/x).
const srcAliases = {
  "@core": resolve("src/core"),
  "@application": resolve("src/application"),
  "@adapters": resolve("src/adapters"),
  "@apps": resolve("src/apps"),
  "@shared": resolve("src/shared"),
};

const production = process.argv[2] === "production";
const watch = process.argv.includes("--watch");
// Output directory is configurable so the build is reproducible outside one
// specific Obsidian vault (stage 1, task 6.4). Defaults to the original vault
// path to preserve existing behavior when the env var is unset.
const defaultOutputDir = join(homedir(), "Documents", "Заметки", ".obsidian", "plugins", "ixplorer");
const pluginOutputDir = process.env.IXPLORER_OUTPUT_DIR ?? defaultOutputDir;
const pluginOutputFile = join(pluginOutputDir, "main.js");

const banner =
  "/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\nif you want to view the source, please visit the plugin repository\n*/";

async function copyPluginAssets() {
  await mkdir(pluginOutputDir, { recursive: true });
  await Promise.all([
    copyFile("manifest.json", join(pluginOutputDir, "manifest.json")),
    copyFile("styles.css", join(pluginOutputDir, "styles.css")),
  ]);
}

await mkdir(pluginOutputDir, { recursive: true });

const context = await esbuild.context({
  alias: srcAliases,
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["src/apps/obsidian/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
    // The Anthropic SDK lazily imports node:fs / node:path for Workload
    // Identity Federation; Obsidian runs on Electron where Node builtins exist
    // at runtime, so externalize the node:-prefixed forms too.
    ...builtins.map((name) => `node:${name}`),
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: pluginOutputFile,
  platform: "browser",
  plugins: [
    {
      name: "copy-plugin-assets",
      setup(build) {
        build.onEnd(async () => {
          await copyPluginAssets();
        });
      },
    },
  ],
  sourcemap: production ? false : "inline",
  target: "es2018",
  treeShaking: true,
});

if (watch) {
  await context.watch();
  console.log(`Watching for changes and writing artifacts to ${pluginOutputDir}...`);
} else {
  await context.rebuild();
  await context.dispose();
}
