export const DEFAULT_INDEX_PROFILE_ID = "default";
export const DEFAULT_INDEX_FOLDER = ".attest/index";
export const DEFAULT_DOWNLOAD_FOLDER = "Attest/Downloads";
export const DEFAULT_ANTHROPIC_MAX_TOKENS = 4096;
export const MAX_INDEX_PROFILE_COUNT = 30;
export const MAX_PROFILE_NAME_LENGTH = 30;
export const DEFAULT_PROFILE_TIMESTAMP = "1970-01-01T00:00:00.000Z";
export const UNVERIFIED_EMBEDDING_SUSPENSION_REASON = "Embedding capability could not be verified.";
export const INVALID_BASE_URL_SUSPENSION_REASON = "The server profile has an invalid base URL.";
